development:
  websocket_url: ws://localhost:8889/web-socket
  publish_url: http://localhost:8889/publish

test:
  websocket_url: ws://localhost:8889/web-socket
  publish_url: http://localhost:8889/publish

production:
  websocket_url: ws://wspubsub.cloudigisafe.com/web-socket
  publish_url: http://wspubsub.cloudigisafe.com/publish
